# TODO: make each services order similar
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - ${NGINX_PORT:-443}:443
    volumes:
      - wordpress:/var/www/html:ro
    depends_on: # todo: wait for healthy
      - wordpress
    restart: unless-stopped
    env_file: ./.env
    secrets:
      - selfsigned.crt
      - selfsigned.key
    develop:
      watch:
        - action: sync+restart
          path: ./requirements/nginx/conf/
          target: /etc/nginx/templates/
        - action: sync+restart
          path: ./requirements/nginx/tools
          target: /tools
        - action: rebuild
          path: ./requirements/nginx/Dockerfile
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./requirements/wordpress/Dockerfile
        - action: sync+restart
          path: ./requirements/wordpress/conf/
          target: /etc/php84/php-fpm.d/
volumes:
  wordpress:
secrets:
  selfsigned.crt:
    file: ${SSL_CRT_FILE:?error}
  selfsigned.key:
    file: ${SSL_KEY_FILE:?error}
