services:
  nginx:
    build: ./requirements/nginx
    ports:
      - ${NGINX_PORT:-443}:${NGINX_PORT:-443}
    volumes:
      - wordpress:/usr/share/nginx/html:ro
    depends_on:
      - wordpress
    env_file: "./.env"
    develop:
      watch:
        - action: sync+restart
          path: ./requirements/nginx/conf/
          target: /etc/nginx/templates/
        - action: sync+restart
          path: ./requirements/nginx/tools
          target: /tools
        - action: rebuild
          path: ./requirements/nginx/Dockerfile
  wordpress:
    image: wordpress:latest
    ports:
      - 9000
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    ports:
      - 3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true" # TODO: tmp
volumes:
  wordpress:
