# TODO: make each services order similar
name: inception
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html:ro
    depends_on:
      wordpress:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    environment:
      NGINX_HOST: ${NGINX_HOST:-jsadjina.42.fr}
    secrets:
      - selfsigned.crt
      - selfsigned.key
    develop:
      watch:
        - action: sync+restart
          path: ./requirements/nginx/conf
          target: /etc/nginx/templates
        - action: sync+restart
          path: ./requirements/nginx/tools
          target: /tools
        - action: rebuild
          path: ./requirements/nginx/Dockerfile
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    environment:
      WORDPRESS_DB_USER: ${DB_USER:-wpuser}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:?error}
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_ADMIN_USER_NAME: ${WORDPRESS_ADMIN_USER_NAME:-420chefe69}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD:?error}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL:?error}
      WORDPRESS_USER_NAME: ${WORDPRESS_USER_NAME:-420author69}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD:?error}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL:?error}
      WORDPRESS_USER_ROLE: ${WORDPRESS_USER_ROLE:-author}
      WORDPRESS_URL: ${NGINX_HOST:-jsadjina.42.fr}
      WORDPRESS_TITEL: ${WORDPRESS_TITEL:-inception}
      WORDPRESS_THEME: ${WORDPRESS_THEME:-twentysixteen}
    develop:
      watch:
        - action: rebuild
          path: ./requirements/wordpress/Dockerfile
        - action: sync+restart
          path: ./requirements/wordpress/conf/
          target: /etc/php84/
        - action: sync+restart
          path: ./requirements/wordpress/tools
          target: /tools
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER:-wpuser}
      DB_NAME: ${DB_NAME:-wordpress}
      DB_PASSWORD: ${DB_PASSWORD:?error}
    develop:
      watch:
        - action: rebuild
          path: ./requirements/mariadb/Dockerfile
        - action: sync+restart
          path: ./requirements/mariadb/conf
          target: /etc/my.cnf.d
        - action: sync+restart
          path: ./requirements/mariadb/tools
          target: /tools
    networks:
      - inception
    ports:
      - 3306:3306
volumes:
  wordpress:
  mariadb:
secrets:
  selfsigned.crt:
    file: ${NGINX_SSL_CRT_FILE:?error}
  selfsigned.key:
    file: ${NGINX_SSL_KEY_FILE:?error}
networks:
  inception:
    name: inception
