# TODO: make each services order similar
name: inception
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443
    volumes:
      - wordpress:/var/www/html:ro
    depends_on:
      wordpress:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    environment:
      NGINX_HOST: ${NGINX_HOST:-jsadjina.42.fr} # TODO: do I need this?
    secrets:
      - selfsigned.crt
      - selfsigned.key
    develop:
      watch:
        - action: sync+restart
          path: ./requirements/nginx/conf
          target: /etc/nginx/templates
        - action: sync+restart
          path: ./requirements/nginx/tools
          target: /tools
        - action: rebuild
          path: ./requirements/nginx/Dockerfile
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./requirements/wordpress/Dockerfile
        - action: sync+restart
          path: ./requirements/wordpress/conf
          target: /etc/php84
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER:-wpuser}
      DB_NAME: ${DB_NAME:-wordpress}
      DB_PASSWORD: ${DB_PASSWORD:?error}
    develop:
      watch:
        - action: rebuild
          path: ./requirements/mariadb/Dockerfile
        - action: sync+restart
          path: ./requirements/mariadb/conf
          target: /etc/my.cnf.d
        - action: sync+restart
          path: ./requirements/mariadb/tools
          target: /tools
volumes:
  wordpress:
  mariadb:
secrets:
  selfsigned.crt:
    file: ${NGINX_SSL_CRT_FILE:?error}
  selfsigned.key:
    file: ${NGINX_SSL_KEY_FILE:?error}
