# TODO: make each services order similar
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - ${NGINX_PORT:-443}:443
    volumes:
      - wordpress:/var/www/html:ro
    depends_on:
      - wordpress
    env_file: ./.env
    secrets:
      - selfsigned.crt
      - selfsigned.key
    develop:
      watch:
        - action: sync+restart
          path: ./requirements/nginx/conf/
          target: /etc/nginx/templates/
        - action: sync+restart
          path: ./requirements/nginx/tools
          target: /tools
        - action: rebuild
          path: ./requirements/nginx/Dockerfile
  wordpress:
    image: wordpress:php8.2-fpm
    ports:
      - 9000
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    ports:
      - 3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true # TODO: tmp
volumes:
  wordpress:
secrets:
  selfsigned.crt:
    file: ${SSL_CRT_FILE:?error}
  selfsigned.key:
    file: ${SSL_KEY_FILE:?error}
